/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(misc_utils/extract_assignment_cmd.h)                       */
/* BINDTOOL_HEADER_FILE_HASH(f476a28b35cf9d9927d17b51d0548061)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gsm/misc_utils/extract_assignment_cmd.h>
// pydoc.h is automatically generated in the build directory
#include <extract_assignment_cmd_pydoc.h>

void bind_extract_assignment_cmd(py::module& m)
{

    using extract_assignment_cmd = ::gr::gsm::extract_assignment_cmd;


    py::class_<extract_assignment_cmd, gr::block, gr::basic_block, std::shared_ptr<extract_assignment_cmd>>(
        m, "extract_assignment_cmd", D(extract_assignment_cmd))

        .def(py::init(&extract_assignment_cmd::make), D(extract_assignment_cmd, make))


        .def("get_assignment_commands",
             &extract_assignment_cmd::get_assignment_commands,
             D(extract_assignment_cmd, get_assignment_commands))

        ;
}
