/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(qa_utils/message_sink.h)                                 */
/* BINDTOOL_HEADER_FILE_HASH(7e943a3891cf685e37cf698eda99fe6f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gsm/qa_utils/message_sink.h>
// pydoc.h is automatically generated in the build directory
#include <message_sink_pydoc.h>

void bind_message_sink(py::module& m)
{

    using message_sink = ::gr::gsm::message_sink;


    py::class_<message_sink, gr::block, gr::basic_block, std::shared_ptr<message_sink>>(
        m, "message_sink", D(message_sink))

        .def(py::init(&message_sink::make), D(message_sink, make))


        .def("get_messages", &message_sink::get_messages, D(message_sink, get_messages))

        ;
}
