/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(decoding/tch_h_decoder.h)                                  */
/* BINDTOOL_HEADER_FILE_HASH(7c6454321200239d12b385aae225dfbd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gsm/decoding/tch_h_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <tch_h_decoder_pydoc.h>

void bind_tch_h_decoder(py::module& m)
{

    using tch_h_decoder = ::gr::gsm::tch_h_decoder;


    py::class_<tch_h_decoder, gr::block, gr::basic_block, std::shared_ptr<tch_h_decoder>>(
        m, "tch_h_decoder", D(tch_h_decoder))

        .def(py::init(&tch_h_decoder::make),
             py::arg("sub_channel"),
             py::arg("multi_rate"),
             py::arg("boundary_check") = false,
             D(tch_h_decoder, make))


        ;
}
